### ISSUE TITLE
Add log level filter

### ISSUE THREAD

**Issue by hacheraw** [kurdin/console-remote-server#8]
Hello!
I'm loving this tool.

Would it be possible to filter log levels in channels?

Right now I'm doing it with CSS, e.g:
```css
span.levels.level-info {
    display: none;
}
```

Also, thanks for the "More information" part on README.md
